aws_region     = "ap-south-1"    
function_name    = "my-lambda-function"
handler          = "main.lambda_handler"
runtime          = "python3.8"
filename         = "./module/lambda/lambda_function/main.zip"
iam_role_name    = "my-lambda-role-test"
